apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helm-test-ingress
  namespace: default
spec:
  dnsNames:
    - napoleon-test3.zapprovedlabs.com
  secretName: example-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer