apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-sre-science-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: team_sre@zapproved.com
    privateKeySecretRef:
      name: letsencrypt-sre-science-issuer-key
    solvers:
    - http01:
       ingress:
         class: zdiscovery-nginx-default
    - http01:
       ingress:
         class: nginx-monitoring